# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MiaSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "Fabric"
  pod "Crashlytics"

  pod "SwiftyJSON", "~> 4.0"
  pod "Alamofire"
  pod "IQKeyboardManagerSwift"
  pod "AlamofireNetworkActivityLogger"
  pod "DropDown", "~> 2.3.2"
  
end
